added ninja build system

diff --git a/scripts/shell/uginstall b/scripts/shell/uginstall
--- a/scripts/shell/uginstall
+++ b/scripts/shell/uginstall
@@ -343,6 +343,7 @@ my_install()
 	fi
 }
 
+
 ######################################################################################################################################################
 # the actual install scripts
 ######################################################################################################################################################
@@ -716,6 +717,26 @@ install_thrift()
 }
 
 
+install_ninja()
+{
+	subdir=ninja
+	if [ -e $subdir/installed ]; then
+		echo "$subdir  already installed."
+	else
+		check_license $subdir
+	
+		git clone git://github.com/martine/ninja.git 
+		cd ninja
+		git checkout release
+		./configure.py --bootstrap
+		if [ ! $? == 0 ]; then 			
+			echo "Error configuring ninja"
+			exit
+		fi
+		source $scriptpath/uginstall_config
+		touch installed
+	fi
+}
 
 ######################################################################################################################################################
 
@@ -867,5 +888,6 @@ case $param1 in
 	cppcheck) install_cppcheck ;;
 	libevent) install_libevent ;;
 	thrift) install_thrift ;;
+	ninja) install_ninja ;;
 	*) print_usage ;;
 esac
