added check for return of qsub/salloc

diff --git a/scripts/shell/schedulers/cekon b/scripts/shell/schedulers/cekon
--- a/scripts/shell/schedulers/cekon
+++ b/scripts/shell/schedulers/cekon
@@ -58,6 +58,16 @@ function UJS_Submit
 
 	if [ $interactive == true ]; then
 		`$sallocrun`
+		return=$?	
+		if [ ! $return == 0 ]; then
+			echo "ERROR! salloc args:"
+			if [ ! $verbose == true ]; then
+				echo "$sallocrun"		
+			fi 
+			echo "ERROR: salloc returned $return. Job has NOT been scheduled."
+			
+			exit
+		fi
 	else
 		nohup $sallocrun > $outdir/job.output &
 	fi
diff --git a/scripts/shell/schedulers/hermit b/scripts/shell/schedulers/hermit
--- a/scripts/shell/schedulers/hermit
+++ b/scripts/shell/schedulers/hermit
@@ -68,7 +68,18 @@ function UJS_Submit
 
 	echo "echo \"cd $outdir; $qsubrun\" | qsub $qsubargs" >> info.txt
 
-	jobid=`echo "cd $outdir; $qsubrun" | qsub $qsubargs`	
+	jobid=`echo "cd $outdir; $qsubrun" | qsub $qsubargs`
+	return=$?	
+	if [ ! $return == 0 ]; then
+		echo "ERROR! qsub args:"
+		if [ ! $verbose == true ]; then
+			echo "echo \"cd $outdir; $qsubrun\" | qsub $qsubargs"		
+		fi 
+		echo "ERROR: qsub returned $return. Job has NOT been scheduled."
+		
+		exit
+	fi
+	
 	jobid=`echo $jobid | sed 's/\([0-9]*\).*/\1/'`
 }
 
diff --git a/scripts/shell/schedulers/new_template b/scripts/shell/schedulers/new_template
--- a/scripts/shell/schedulers/new_template
+++ b/scripts/shell/schedulers/new_template
@@ -32,6 +32,16 @@ function UJS_Submit
 		# display more information, and also the actual call to the scheduler
 	fi
 
+	# call your scheduler command
+
+	# please check the return of your scheduler command:
+	
+	return=$?
+	if [ ! $return == 0 ]; then
+		echo "ERROR: scheduler returned $return. Job has NOT been scheduled."		
+		exit
+	fi
+	
 	# you should write the job id in the variable jobid, for example	
 	# sleep 1
 	# jobid=`cat job.output | sed -n 1p | sed 's/salloc: Granted job allocation \([0-9]*\).*/\1/'`
